services:
  - type: web
    name: sglory-futsal
    runtime: docker
    plan: free
    branch: main
    autoDeploy: yes
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sglory-futsal-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000

databases:
  - name: sglory-futsal-db
    plan: free
    databaseName: sglory_futsal
